name: Build and Push Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_uri: ${{ steps.meta.outputs.image_uri }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Login to ECR (eu-north-1)
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        id: meta
        env:
          AWS_REGION: eu-north-1
          REPO_NAME: umami
          TAG: ${{ github.sha }}
        run: |
          set -euo pipefail
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$TAG"

          docker build \
            --build-arg DATABASE_URL="${{ secrets.UMAMI_BUILD_DATABASE_URL }}" \
            -t "$IMAGE_URI" .
           if [ -z "${{ secrets.UMAMI_BUILD_DATABASE_URL }}" ]; then
             echo "ERROR: UMAMI_BUILD_DATABASE_URL secret is empty or not available to this workflow"
             exit 1
           else
             echo "UMAMI_BUILD_DATABASE_URL secret is present"
           fi

  
          docker push "$IMAGE_URI"
          echo "IMAGE_URI=$IMAGE_URI" >> "$GITHUB_ENV"